name: "deploy"
description: "This action deploys the pax and tar in artifactory"

runs:
  using: "composite"
  steps:
    - name: 'deploy'
      run: |
        TIMESTAMP=`date +%Y%m%d.%H%M%S`
        mv zlux.pax zlux-core-${ZOWE_VERSION}-${TIMESTAMP}.pax
        mv zlux.tar zlux-core-${ZOWE_VERSION}-${TIMESTAMP}.tar
        
        jfrog rt u zlux-core-${ZOWE_VERSION}-${TIMESTAMP}.pax ${ARTIFACTORY_REPO}/zlux-core/${ZOWE_VERSION}-RC/zlux-core-${ZOWE_VERSION}-${TIMESTAMP}.pax
        jfrog rt u zlux-core-${ZOWE_VERSION}-${TIMESTAMP}.tar ${ARTIFACTORY_REPO}/zlux-core/${ZOWE_VERSION}-RC/zlux-core-${ZOWE_VERSION}-${TIMESTAMP}.tar
        echo "${ARTIFACTORY_REPO}/zlux-core/${ZOWE_VERSION}-RC/zlux-core-${ZOWE_VERSION}-${TIMESTAMP}.pax"
        echo "${ARTIFACTORY_REPO}/zlux-core/${ZOWE_VERSION}-RC/zlux-core-${ZOWE_VERSION}-${TIMESTAMP}.tar"
        
      shell: bash