name: Create Release Branch

env:
JENKINS_NODE = "zlux-agent"
GITHUB_PROJECT = "zowe"
GITHUB_SSH_KEY = "zlux-jenkins"
RELEASE_BRANCH = "v2.x/rc"
MASTER_BRANCH = "v2.x/master"

GITHUB_TOKEN:${{secrets.GITHUB_TOKEN}}
REPOS = [

    "zlux-app-manager"
]
on:
  workflow_dispatch:
    inputs:
      RELEASE_VERSION:
        description: 'Name of version'
        required: true
jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:
    - name: make release
      run: tagName = ${{ github.event.inputs.RELEASE_VERSION}}
           name  = ${{ github.event.inputs.RELEASE_VERSION}}
            curl --request POST \ --url "https://api.github.com/repos/zowe/zlux-app-manager/releases" \
            --authentication env.GITHUB_TOKEN\
            --data \
            {
              "tag_name": "${tagName}",
              "target_commitish": "v2.x/master",
               "name": "${name}",
               "body": "",
                "draft": false,
                "prerelease": false
            }